# Generated by Django 5.2 on 2025-04-09 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='user_identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='audiorecording',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
        migrations.AlterField(
            model_name='audiorecording',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='audiorecording',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL),
        ),
    ]
