# Generated by Django 5.2 on 2025-04-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_audiorecording_user_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecording',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='audiorecording',
            name='user_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
